name       : libxaw
version    : 1.0.13
release    : 8
source     :
    - http://xorg.freedesktop.org/releases/individual/lib/libXaw-1.0.13.tar.gz : 7e74ac3e5f67def549722ff0333d6e6276b8becd9d89615cda011e71238ab694
license    :
    - MIT
summary    : X11 Athena Widget library
component  : xorg.library
description: |
    Xaw is the X Athena Widget Set. Xaw is a widget set based on the X Toolkit Intrinsics (Xt) Library.
builddeps  :
    - pkgconfig32(x11)
    - pkgconfig32(xmu)
    - pkgconfig32(xpm)
    - pkgconfig32(xext)
    - pkgconfig32(xt)
optimize   : speed
emul32     : yes
patterns   :
    - devel :
        - /usr/share/man
        - /usr/share/doc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
